In [3]:
import numpy as np
import matplotlib.pyplot as plt 
import tensorflow as tf
from tensorflow import keras
import pandas as pd
%matplotlib inline

In [6]:
df = pd.read_csv('insurance_data.csv')
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              1                 0
4   46              0                 1

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25
)

In [9]:
X_train.head()

    age  affordibility
0    22              1
13   29              1
6    55              0
17   58              0
24   50              1